<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Cosmetic_Store_Management_System.Core</RootNamespace>
    <Platforms>AnyCPU;x64;x86</Platforms>
    <Platforms>x86;x64;arm64;AnyCPU</Platforms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CommunityToolkit.WinUI.Controls.Primitives" Version="8.1.240916" />
    <PackageReference Include="CSharpMarkup.WinUI.LiveChartsCore.SkiaSharpView" Version="2.4.18" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Npgsql" Version="8.0.5" />
    <PackageReference Include="PropertyChanged.Fody" Version="4.1.0" />
  </ItemGroup>
</Project>
